name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'


      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends apptainer \
            || sudo apt-get install -y --no-install-recommends singularity-container
          if ! command -v apptainer >/dev/null && command -v singularity >/dev/null; then
            sudo ln -s $(command -v singularity) /usr/local/bin/apptainer
          fi
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo rm -rf /usr/share/doc /usr/share/man /usr/share/locale

      - name: Restore Apptainer cache
        id: cache-dir
        uses: actions/cache@v3
        with:
          path: sifs/.cache
          key: ${{ runner.os }}-apptainer-cache-${{ hashFiles('sifs/get_image.sh') }}

      - name: Restore SIF from cache
        id: cache-sif
        uses: actions/cache@v3
        with:
          path: sifs/ompc-base_latest.sif
          key: ${{ runner.os }}-sif-${{ hashFiles('sifs/get_image.sh') }}

      - name: Download SIF image
        if: steps.cache-sif.outputs.cache-hit != 'true'
        env:
          APPTAINER_CACHEDIR: ${{ github.workspace }}/sifs/.cache
          SINGULARITY_CACHEDIR: ${{ github.workspace }}/sifs/.cache
          APPTAINER_TMPDIR: ${{ github.workspace }}/sifs/.cache/tmp
        run: |
          cd sifs
          bash get_image.sh

      - name: Validate Python scripts
        run: |
          python -m py_compile $(git ls-files '*.py')
