name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake clang liburing-dev gnupg wget lsb-release
          DISTRO=$(lsb_release -cs)
          wget -qO - https://repo.radeon.com/rocm/rocm.gpg.key | sudo apt-key add -
          echo "deb [arch=amd64] https://repo.radeon.com/rocm/apt/6.4/ ${DISTRO} main" | sudo tee /etc/apt/sources.list.d/rocm.list
          sudo apt-get update
          sudo apt-get install -y rocm-hip-sdk

      - name: Validate Python scripts
        run: |
          python -m py_compile $(git ls-files '*.py')

      - name: Build final demo
        run: |
          cd application/uring_print_mt_svm
          clang++ -fopenmp -fopenmp-targets=amdgcn-amd-amdhsa \
            --offload-arch=gfx908 -Iinclude src/*.cpp \
            -L/opt/rocm/lib -L/opt/rocm/lib64 -lhsa-runtime64 -o demo

      - name: Validate Python scripts
        run: |
          python -m py_compile $(git ls-files '*.py')

      - name: Build demo and check output
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake liburing-dev
          cd application/uring_print_mt
          mkdir build && cd build
          cmake ..
          cmake --build . -- VERBOSE=1
          ./demo 2>actual_output.txt
          sort -V actual_output.txt >sorted_actual.txt
          diff -u ../example_output.txt sorted_actual.txt
